Password (20)

To prepare for PAT, the judge sometimes has to generate random passwords for the users. 
The problem is that there are always some confusing passwords since it is hard to distinguish 
	1 (one) from l (L in lowercase), 
	0 (zero) from O (o in uppercase). 
One solution is to 
	replace 1 (one) by @, 
	0 (zero) by %, 
	l by L, 
	and O by o. 
Now it is your job to write a program to check the accounts generated by the judge, 
and to help the juge modify the confusing passwords.

Input Specification:
Each input file contains one test case. Each case contains a positive integer N (<= 1000), 
followed by N lines of accounts. Each account consists of a user name and a password, 
both are strings of no more than 10 characters with no space.

Output Specification:
For each test case, first print the number M of accounts that have been modified, 
then print in the following M lines the modified accounts info, 
that is, the user names and the corresponding modified passwords. 
The accounts must be printed in the same order as they are read in. 
If no account is modified, 
print in one line "There are N accounts and no account is modified" where N is the total number of accounts. 
However, if N is one, you must print "There is 1 account and no account is modified" instead.


Sample Input 1:
3
Team000002 Rlsp0dfa
Team000003 perfectpwd
Team000001 R1spOdfa
Sample Output 1:
2
Team000002 RLsp%dfa
Team000001 R@spodfa


Sample Input 2:
1
team110 abcdefg332
Sample Output 2:
There is 1 account and no account is modified


Sample Input 3:
2
team110 abcdefg222
team220 abcdefg333
Sample Output 3:
There are 2 accounts and no account is modified


1 by @
0 by %
l by L
O by o


#include <cstdio>
#include <cstring>

const int MAXN = 10010;

int N, num = 0, num2 = 0, tag[MAXN];

struct node{
	char userName[MAXN];
	char passWord[MAXN];
} Node[MAXN];

bool check(int i) {
	int flag = 0;
	int len = strlen(Node[i].passWord);
	for(int j=0; j<len; j++) {
		if(Node[i].passWord[j] == '1') {
			Node[i].passWord[j] = '@';
			flag = 1;
		}
		if(Node[i].passWord[j] == '0') {
			Node[i].passWord[j] = '%';
			flag = 1;
		}
		if(Node[i].passWord[j] == 'l') {
			Node[i].passWord[j] = 'L';
			flag = 1;
		}
		if(Node[i].passWord[j] == 'O') {
			Node[i].passWord[j] = 'o';  //
			flag = 1;
		}
	}
	
	if(flag == 1) return true;
	else return false;
}

int main() {
	// 输入
	scanf("%d",&N);
	for(int i=0; i<N; i++) {
		scanf("%s %s",Node[i].userName,Node[i].passWord);  ////// %s %s间有空格； //////Node[i].userName前无&
	}
	// 查找并替换
	for(int i=0; i<N; i++) {
		if(check(i)) {
			num++;
			tag[i] = 1; 
		}
	}
	// 输出
	if(num == 0) {
		printf("There is %d account and no account is modified",N);
		return 0;
	}
	printf("%d\n",num);
	for(int i=0; i<N; i++) {
		if(tag[i] == 1) {
			printf("%s %s",Node[i].userName,Node[i].passWord);
			num2 ++;
			if(num2 != num) printf("\n");
		}
	}

	return 0;
}


17' 一个测试点出错  ？？？